# Generated by Django 5.1.2 on 2024-10-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_employeeeducation_employeeexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeeducation',
            name='coursehsc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
